Teacher.create("name"=>"Jacques")
Teacher.create("name"=>"Louis")
Teacher.create("name"=>"Fred")
Teacher.create("name"=>"John")
Article.create("name"=>"Excursion in Russia", "description"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tincidunt quam quis felis pulvinar semper. Donec auctor augue facilisis, sollicitudin ante nec, malesuada eros. Donec dignissim commodo eros nec tincidunt. Duis in ultricies nisl, vel facilisis purus. Maecenas ac viverra sapien, quis elementum sapien. Proin cursus diam ac blandit lacinia. Etiam nisi justo, vehicula et fermentum sit amet, convallis a magna. Quisque ullamcorper felis a facilisis malesuada.", "teacher_id"=>4)
Article.create("name"=>"Small excursion in Europe", "description"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tincidunt quam quis felis pulvinar semper. Donec auctor augue facilisis, sollicitudin ante nec, malesuada eros.", "teacher_id"=>4)
Article.create("name"=>"Excursion in India", "description"=>"Aliquam non tempus orci, in laoreet nunc. Phasellus eu condimentum sapien. Vivamus bibendum orci ac lacinia facilisis. Duis pharetra massa vel velit fermentum, sit amet tincidunt tortor dapibus. Nullam non urna sit amet libero tempor maximus in ac ex. Morbi ac orci at ante vehicula sagittis sed pellentesque odio. Vestibulum placerat risus ipsum, id ultricies lectus gravida et. Cras iaculis metus eu nibh euismod maximus. Ut malesuada aliquam massa, ac feugiat odio consequat vel. Proin efficitur lobortis facilisis. Duis placerat turpis id cursus maximus. Maecenas sodales, orci sollicitudin tincidunt lacinia, dolor diam luctus sem, scelerisque tincidunt felis mi quis erat. Quisque eu felis ut tortor sagittis mollis eget non diam.", "teacher_id"=>4)
Article.create("name"=>"Small excursions in Australia", "description"=>"Visited Melbourne, Brisbane", "teacher_id"=>1)
Excursion.create("article_id"=>1, "student_id"=>1, "excursion_date"=>'Mon, 11 Jul 2021 03:17:12.965513000')
Excursion.create("article_id"=>2, "student_id"=>6, "excursion_date"=>'Mon, 23 Apr 2021 03:17:12.965513000')
Excursion.create("article_id"=>3, "student_id"=>4, "excursion_date"=>'Mon, 18 Jun 2021 03:17:12.965513000')
Excursion.create("article_id"=>7, "student_id"=>2, "excursion_date"=>'Mon, 20 Mar 2021 03:17:12.965513000')
Excursion.create("article_id"=>7, "student_id"=>5, "excursion_date"=>'Mon, 20 Mar 2021 03:17:12.965513000')
Excursion.create("article_id"=>3, "student_id"=>7, "excursion_date"=>'Mon, 18 Jun 2021 03:17:12.965513000')
Excursion.create("article_id"=>2, "student_id"=>8, "excursion_date"=>'Mon, 23 Apr 2021 03:17:12.965513000')
Excursion.create("article_id"=>1, "student_id"=>2, "excursion_date"=>'Mon, 11 Jul 2021 03:17:12.965513000')
Student.create("name"=>"Jean")
Student.create("name"=>"Marc")
Student.create("name"=>"Silvye")
Student.create("name"=>"Thierry")
Student.create("name"=>"Bob")
Student.create("name"=>"Jade")
Student.create("name"=>"Jason")
Student.create("name"=>"Boubakar")
Student.create("name"=>"Jimmy")
Student.create("name"=>"Damien")

